base_url = "https://dragove.site"
compile_sass = true
minify_html = true
title = "鸽子窝"
description = "随便记录的内容"

taxonomies = [
    { name = "tags", feed = true},
    { name = "archives", feed = true}
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"

[extra]